SELECT
  [RecordID],
  [Account],
  [Status],
  [RecordType],
  [Posted],
  [JournalID],
  [BatchID],
  [Date],
  [Document],
  [Description],
  [Amount],
  [CreateUser],
  [UpdateUser],
  [CreateDate],
  [AllocId],
  [AllocGrp],
  [VendorId],
  [1099Type],
  [CmpnyID],
  [BrUnpost],
  [Name],
  [Job],
  [CostType],
  [Moved],
  [TransClass1],
  [TransClass2],
  [CostCode],
  [PostedToParent],
  [GrantId],
  [CoreObjExpns],
  [FundSrc],
  [Program],
  [Activity],
  [CustId],
  [Unused],
  LEFT([Account], 5) AS [Base],
  CONCAT(
    [Job],
    [CostCode],
    STR([CostType], 2, 0),
    [Document],
    [JournalID],
    LEFT([Account], 5),
    STR([Amount], 18, 2),
    ROW_NUMBER() OVER (
      PARTITION BY [Job],
      [CostCode],
      STR([CostType], 2, 0),
      [Document],
      [JournalID],
      LEFT([Account], 5),
      STR([Amount], 18, 2)
      ORDER BY
        [Job]
    )
  ) AS GL_Key
FROM
  [CYMA].[dbo].[SDSP_GL_Trx3]
UNION
ALL
SELECT
  [RecordID],
  [Account],
  [Status],
  [RecordType],
  [Posted],
  [JournalID],
  [BatchID],
  [Date],
  [Document],
  [Description],
  [Amount],
  [CreateUser],
  [UpdateUser],
  [CreateDate],
  [AllocId],
  [AllocGrp],
  [VendorId],
  [1099Type],
  [CmpnyID],
  [BrUnpost],
  [Name],
  [Job],
  [CostType],
  [Moved],
  [TransClass1],
  [TransClass2],
  [CostCode],
  [PostedToParent],
  [GrantId],
  [CoreObjExpns],
  [FundSrc],
  [Program],
  [Activity],
  [CustId],
  [Unused],
  LEFT([Account], 5) AS [Base],
  CONCAT(
    [Job],
    [CostCode],
    STR([CostType], 2, 0),
    [Document],
    [JournalID],
    LEFT([Account], 5),
    STR([Amount], 18, 2),
    ROW_NUMBER() OVER (
      PARTITION BY [Job],
      [CostCode],
      STR([CostType], 2, 0),
      [Document],
      [JournalID],
      LEFT([Account], 5),
      STR([Amount], 18, 2)
      ORDER BY
        [Job]
    )
  ) AS GL_Key
FROM
  [CYMA].[dbo].[SDSP_GL_Trx3H];