SELECT
  [RecNo],
  [TransType],
  [Source],
  [LineId],
  [LineNo],
  [TransDate],
  [ID],
  [Name],
  [Job],
  [ProdId],
  [ProdDesc],
  [CostType],
  [SkillId],
  [SkillDesc],
  [UnitofM],
  [AccountId],
  [OrigUnits],
  [OrigCost],
  [OrigRate],
  [OrigAmt],
  [AdjUnits],
  [MarkUpPct],
  [MarkUpAmt],
  [AdjRate],
  [BillAmt],
  [ARUpdate],
  [LaborChg],
  [Year],
  [Period],
  [BilledUnits],
  [BilledDate],
  [Status],
  [Applied],
  [CostCode],
  [ProfitAmt],
  [TransClass1],
  [TransClass2],
  [OvhType],
  [BuildNo],
  [Measure],
  [Costed],
  [CostCat],
  [OvhYear],
  [OvhPrd],
  [OvhAmt],
  [OvhPct],
  [FringeAmt],
  [FringePct],
  [GAAmt],
  [GAPct],
  [EarnType],
  [InvAmt],
  [InvDate],
  [PymtAmt],
  [PymtDate],
  [OvhBillAmt],
  [PostGlRcdId],
  [CreatedBy],
  [CreatedDate],
  [UpdatedBy],
  [UpdatedDate],
  [GrantId],
  [CoreObjExpns],
  [Program],
  [Activity],
  [Certified],
  [UnUsed],
  LEFT([AccountId], 5) AS [Base],
  CONCAT(
    [Job],
    [CostCode],
    STR([CostType], 2, 0),
    [LineID],
    [Source],
    LEFT([AccountId], 5),
    STR([OrigAmt], 18, 2),
    ROW_NUMBER() OVER (
      PARTITION BY [Job],
      [CostCode],
      STR([CostType], 2, 0),
      [LineID],
      [Source],
      LEFT([AccountId], 5),
      STR([OrigAmt], 18, 2)
      ORDER BY
        [Job]
    )
  ) AS JC_Key
FROM
  [CYMA].[dbo].[SDSP_Jc_Trx3]
UNION
ALL
SELECT
  [RecNo],
  [TransType],
  [Source],
  [LineId],
  [LineNo],
  [TransDate],
  [ID],
  [Name],
  [Job],
  [ProdId],
  [ProdDesc],
  [CostType],
  [SkillId],
  [SkillDesc],
  [UnitofM],
  [AccountId],
  [OrigUnits],
  [OrigCost],
  [OrigRate],
  [OrigAmt],
  [AdjUnits],
  [MarkUpPct],
  [MarkUpAmt],
  [AdjRate],
  [BillAmt],
  [ARUpdate],
  [LaborChg],
  [Year],
  [Period],
  [BilledUnits],
  [BilledDate],
  [Status],
  [Applied],
  [CostCode],
  [ProfitAmt],
  [TransClass1],
  [TransClass2],
  [OvhType],
  [BuildNo],
  [Measure],
  [Costed],
  [CostCat],
  [OvhYear],
  [OvhPrd],
  [OvhAmt],
  [OvhPct],
  [FringeAmt],
  [FringePct],
  [GAAmt],
  [GAPct],
  [EarnType],
  [InvAmt],
  [InvDate],
  [PymtAmt],
  [PymtDate],
  [OvhBillAmt],
  [PostGlRcdId],
  [CreatedBy],
  [CreatedDate],
  [UpdatedBy],
  [UpdatedDate],
  [GrantId],
  [CoreObjExpns],
  [Program],
  [Activity],
  [Certified],
  [UnUsed],
  LEFT([AccountId], 5) AS [Base],
  CONCAT(
    [Job],
    [CostCode],
    STR([CostType], 2, 0),
    [LineID],
    [Source],
    LEFT([AccountId], 5),
    STR([OrigAmt], 18, 2),
    ROW_NUMBER() OVER (
      PARTITION BY [Job],
      [CostCode],
      STR([CostType], 2, 0),
      [LineID],
      [Source],
      LEFT([AccountId], 5),
      STR([OrigAmt], 18, 2)
      ORDER BY
        [Job]
    )
  ) AS JC_Key
FROM
  [CYMA].[dbo].[SDSP_Jc_TrxH3];